"""add_dynamic_targets

Revision ID: 1e62046a113b
Revises: 7094c1ea5471
Create Date: 2026-01-29 08:52:55.265914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e62046a113b'
down_revision: Union[str, None] = '7094c1ea5471'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('targets',
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('target_id')
    )
    op.create_index(op.f('ix_targets_code'), 'targets', ['code'], unique=True)
    op.create_table('form_targets',
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['clinical_forms.form_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.target_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('form_id', 'target_id')
    )
    op.drop_column('clinical_forms', 'target')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_forms', sa.Column('target', postgresql.ENUM('TODAS', 'EMBARAZADAS', 'POST_PARTO', 'MENOPAUSIA', 'LACTANCIA', 'DEPORTISTA', name='targettype'), autoincrement=False, nullable=True))
    op.drop_table('form_targets')
    op.drop_index(op.f('ix_targets_code'), table_name='targets')
    op.drop_table('targets')
    # ### end Alembic commands ###
