"""Initial migration

Revision ID: 2649cc7340ef
Revises: 
Create Date: 2025-11-26 12:46:54.243614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2649cc7340ef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_campaigns',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('sponsor_name', sa.String(), nullable=True),
    sa.Column('asset_url', sa.String(), nullable=True),
    sa.Column('target_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('campaign_id')
    )
    op.create_table('ad_placements',
    sa.Column('placement_id', sa.UUID(), nullable=False),
    sa.Column('location_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('placement_id')
    )
    op.create_table('ai_rag_sources',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('vector_id', sa.String(), nullable=True),
    sa.Column('citation_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('audit_access_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('resource_accessed', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('clinical_forms',
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('form_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('content_translations',
    sa.Column('translation_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('language_code', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('translation_id')
    )
    op.create_table('currencies',
    sa.Column('currency_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('currency_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('exercises',
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('internal_code', sa.String(), nullable=True),
    sa.Column('video_path', sa.String(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('exercise_id'),
    sa.UniqueConstraint('internal_code')
    )
    op.create_table('learning_paths',
    sa.Column('path_id', sa.UUID(), nullable=False),
    sa.Column('name_key', sa.String(), nullable=True),
    sa.Column('target_profile', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('path_id')
    )
    op.create_table('organizations',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('CLINIC', 'GYM', 'COMPANY', name='organizationtype'), nullable=True),
    sa.Column('logo_storage_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('organization_id')
    )
    op.create_table('seasons',
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('season_id')
    )
    op.create_table('session_templates',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('exercises_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_table('subscription_plans',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('stripe_product_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_table('system_settings',
    sa.Column('setting_key', sa.String(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('setting_key')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('firebase_uid', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_table('account_deletion_requests',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('request_date', sa.DateTime(), nullable=True),
    sa.Column('scheduled_deletion_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', name='deletionstatus'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('ai_conversations',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_table('ai_optimizations',
    sa.Column('optimization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('DIFFICULTY_ADJUSTMENT', 'CONTENT_RECOMMENDATION', 'RISK_ALERT', name='optimizationtype'), nullable=True),
    sa.Column('predicted_value', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('optimization_id')
    )
    op.create_table('clinical_snapshots',
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_table('form_sections',
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('form_id', sa.UUID(), nullable=True),
    sa.Column('title_key', sa.String(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['clinical_forms.form_id'], ),
    sa.PrimaryKeyConstraint('section_id')
    )
    op.create_table('path_nodes',
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('path_id', sa.UUID(), nullable=True),
    sa.Column('coordinate_x', sa.Integer(), nullable=True),
    sa.Column('coordinate_y', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('LESSON', 'QUIZ', 'CHALLENGE', 'REWARD', name='nodetype'), nullable=True),
    sa.ForeignKeyConstraint(['path_id'], ['learning_paths.path_id'], ),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.create_table('profiles',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('avatar_storage_path', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('preferred_language', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('scoring_logic',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('form_id', sa.UUID(), nullable=True),
    sa.Column('condition_expression', sa.Text(), nullable=True),
    sa.Column('outcome_score', sa.Integer(), nullable=True),
    sa.Column('outcome_tag', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['clinical_forms.form_id'], ),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_table('shop_catalog',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('name_key', sa.String(), nullable=True),
    sa.Column('cost_currency_id', sa.UUID(), nullable=True),
    sa.Column('cost_amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cost_currency_id'], ['currencies.currency_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('teams',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('user_daily_assignments',
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'SKIPPED', name='assignmentstatus'), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['session_templates.template_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('user_submissions',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('form_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['clinical_forms.form_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_table('user_subscriptions',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELED', 'EXPIRED', 'PAST_DUE', name='subscriptionstatus'), nullable=True),
    sa.Column('ad_free_enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.plan_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('subscription_id')
    )
    op.create_table('user_wallet',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('currency_id', sa.UUID(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.currency_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('wallet_id')
    )
    op.create_table('affiliations',
    sa.Column('affiliation_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'MEDIC', 'TRAINER', 'MEMBER', name='roletype'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.profile_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('affiliation_id')
    )
    op.create_table('ai_messages',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('sender', sa.Enum('USER', 'AI', 'SYSTEM', name='sendertype'), nullable=True),
    sa.Column('content_encrypted', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.conversation_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('form_questions',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('SINGLE_CHOICE', 'MULTIPLE_CHOICE', 'SCALE', 'TEXT', name='questiontype'), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['form_sections.section_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('node_content',
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('reference_type', sa.Enum('VIDEO', 'ARTICLE', 'EXERCISE', 'FORM', name='referencetype'), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['path_nodes.node_id'], ),
    sa.PrimaryKeyConstraint('content_id')
    )
    op.create_table('node_requirements',
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=True),
    sa.Column('required_node_id', sa.UUID(), nullable=True),
    sa.Column('min_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['path_nodes.node_id'], ),
    sa.ForeignKeyConstraint(['required_node_id'], ['path_nodes.node_id'], ),
    sa.PrimaryKeyConstraint('requirement_id')
    )
    op.create_table('optimization_feedback',
    sa.Column('feedback_id', sa.UUID(), nullable=False),
    sa.Column('optimization_id', sa.UUID(), nullable=True),
    sa.Column('user_action', sa.Enum('ACCEPTED', 'REJECTED', 'IGNORED', name='useraction'), nullable=True),
    sa.Column('outcome_metric', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['optimization_id'], ['ai_optimizations.optimization_id'], ),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_table('professional_links',
    sa.Column('link_id', sa.UUID(), nullable=False),
    sa.Column('medic_profile_id', sa.UUID(), nullable=True),
    sa.Column('patient_profile_id', sa.UUID(), nullable=True),
    sa.Column('security_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'REVOKED', name='linkstatus'), nullable=True),
    sa.ForeignKeyConstraint(['medic_profile_id'], ['profiles.profile_id'], ),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['profiles.profile_id'], ),
    sa.PrimaryKeyConstraint('link_id')
    )
    op.create_table('session_performance',
    sa.Column('performance_id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=True),
    sa.Column('duration_actual', sa.Integer(), nullable=True),
    sa.Column('perceived_exertion', sa.Integer(), nullable=True),
    sa.Column('pain_reported', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['user_daily_assignments.assignment_id'], ),
    sa.PrimaryKeyConstraint('performance_id')
    )
    op.create_table('transactions',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['wallet_id'], ['user_wallet.wallet_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('user_inventory',
    sa.Column('inventory_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('item_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['shop_catalog.item_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('inventory_id')
    )
    op.create_table('user_path_progress',
    sa.Column('progress_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('node_id', sa.UUID(), nullable=True),
    sa.Column('stars_earned', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['path_nodes.node_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('progress_id')
    )
    op.create_table('submission_answers',
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=True),
    sa.Column('question_id', sa.UUID(), nullable=True),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['form_questions.question_id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['user_submissions.submission_id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission_answers')
    op.drop_table('user_path_progress')
    op.drop_table('user_inventory')
    op.drop_table('transactions')
    op.drop_table('session_performance')
    op.drop_table('professional_links')
    op.drop_table('optimization_feedback')
    op.drop_table('node_requirements')
    op.drop_table('node_content')
    op.drop_table('form_questions')
    op.drop_table('ai_messages')
    op.drop_table('affiliations')
    op.drop_table('user_wallet')
    op.drop_table('user_subscriptions')
    op.drop_table('user_submissions')
    op.drop_table('user_daily_assignments')
    op.drop_table('teams')
    op.drop_table('shop_catalog')
    op.drop_table('scoring_logic')
    op.drop_table('profiles')
    op.drop_table('path_nodes')
    op.drop_table('form_sections')
    op.drop_table('clinical_snapshots')
    op.drop_table('ai_optimizations')
    op.drop_table('ai_conversations')
    op.drop_table('account_deletion_requests')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_table('subscription_plans')
    op.drop_table('session_templates')
    op.drop_table('seasons')
    op.drop_table('organizations')
    op.drop_table('learning_paths')
    op.drop_table('exercises')
    op.drop_table('currencies')
    op.drop_table('content_translations')
    op.drop_table('clinical_forms')
    op.drop_table('audit_access_logs')
    op.drop_table('ai_rag_sources')
    op.drop_table('ad_placements')
    op.drop_table('ad_campaigns')
    # ### end Alembic commands ###
