"""add_settings_to_profile

Revision ID: 2c3bfff89328
Revises: 7a4612022ba8
Create Date: 2026-04-27 20:07:09.402393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c3bfff89328'
down_revision: Union[str, None] = '7a4612022ba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('notifications_enabled', sa.Boolean(), nullable=True))
    op.add_column('profiles', sa.Column('dark_mode', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'dark_mode')
    op.drop_column('profiles', 'notifications_enabled')
    # ### end Alembic commands ###
