"""Add biometrics to profile

Revision ID: 31eb6d8a0e7f
Revises: 2649cc7340ef
Create Date: 2025-11-26 14:33:20.003870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31eb6d8a0e7f'
down_revision: Union[str, None] = '2649cc7340ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('profiles', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('profiles', sa.Column('birth_date', sa.DateTime(), nullable=True))
    op.add_column('profiles', sa.Column('gender', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'gender')
    op.drop_column('profiles', 'birth_date')
    op.drop_column('profiles', 'height')
    op.drop_column('profiles', 'weight')
    # ### end Alembic commands ###
