"""add_target_id_to_scoring_rule

Revision ID: 38969006f6f8
Revises: 1e62046a113b
Create Date: 2026-02-09 06:15:09.202221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38969006f6f8'
down_revision: Union[str, None] = '1e62046a113b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scoring_rules', sa.Column('target_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'scoring_rules', 'targets', ['target_id'], ['target_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scoring_rules', type_='foreignkey')
    op.drop_column('scoring_rules', 'target_id')
    # ### end Alembic commands ###
