"""Add education module

Revision ID: 6c58fb09053f
Revises: 31eb6d8a0e7f
Create Date: 2025-11-26 14:33:59.862021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c58fb09053f'
down_revision: Union[str, None] = '31eb6d8a0e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education_modules',
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('ARTICLE', 'VIDEO', 'TIP', name='educationtype'), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('module_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('education_modules')
    # ### end Alembic commands ###
