"""add_recommendation_and_streak

Revision ID: 7094c1ea5471
Revises: dc10778e65d4
Create Date: 2026-01-26 06:42:26.803627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7094c1ea5471'
down_revision: Union[str, None] = 'dc10778e65d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_rules',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('condition_expression', sa.Text(), nullable=True),
    sa.Column('target_form_code', sa.String(), nullable=True),
    sa.Column('action_type', sa.Enum('ASSIGN_TRAINING', 'SEND_EMAIL', 'UNLOCK_CONTENT', name='ruleactiontype'), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('action_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_table('user_streaks',
    sa.Column('streak_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('max_streak', sa.Integer(), nullable=True),
    sa.Column('last_activity_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('streak_id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_streaks')
    op.drop_table('recommendation_rules')
    # ### end Alembic commands ###
