"""add_profile_targets_relationship

Revision ID: 7a4612022ba8
Revises: d750006f229e
Create Date: 2026-03-30 19:57:42.494510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a4612022ba8'
down_revision: Union[str, None] = 'd750006f229e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_targets',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.profile_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.target_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'target_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_targets')
    # ### end Alembic commands ###
