"""add_temporal_clinical_fields

Revision ID: d750006f229e
Revises: 091f68fe94a0
Create Date: 2026-03-30 19:17:53.409543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd750006f229e'
down_revision: Union[str, None] = '091f68fe94a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('profiles', sa.Column('delivery_date', sa.DateTime(), nullable=True))
    op.add_column('profiles', sa.Column('last_period_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'last_period_date')
    op.drop_column('profiles', 'delivery_date')
    op.drop_column('profiles', 'due_date')
    # ### end Alembic commands ###
