"""add_nomenclature_fields

Revision ID: dfb82dfaebb0
Revises: 48468e4dd25d
Create Date: 2026-01-19 10:29:08.261115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfb82dfaebb0'
down_revision: Union[str, None] = '48468e4dd25d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_questions', sa.Column('id_pregunta', sa.String(), nullable=True))
    op.add_column('form_questions', sa.Column('data_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_form_questions_data_key'), 'form_questions', ['data_key'], unique=False)
    op.create_index(op.f('ix_form_questions_id_pregunta'), 'form_questions', ['id_pregunta'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_questions_id_pregunta'), table_name='form_questions')
    op.drop_index(op.f('ix_form_questions_data_key'), table_name='form_questions')
    op.drop_column('form_questions', 'data_key')
    op.drop_column('form_questions', 'id_pregunta')
    # ### end Alembic commands ###
